CREATE DATABASE IF NOT EXISTS `download` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci; 

USE `download`;

CREATE TABLE IF NOT EXISTS `task` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`src` VARCHAR(500) NOT NULL,
	`dst` VARCHAR(500) NOT NULL,
	`md5` VARCHAR(32) NOT NULL,
	`status` INT NOT NULL DEFAULT 0,
	`create_time` DATETIME NOT NULL,
	`finish_time` DATETIME DEFAULT NULL,
	`retry_count` INT NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;